
title = { 'Problem 2: Even Fibonacci' }

description = {
    """
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
}

solve = {
    def num1 = 1
    def num2 = 2

    def sum = 2
    while (num2 < 4000000) {
        def old = num2

        // Fibonacci sequence:
        num2 = num1 + num2
        num1 = old

        if (num2 % 2 == 0) {
            sum += num2
        }
    }
    return sum
}
