package com.walshcorp.projecteuler;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n - 1)/2. The first
 * ten pentagonal numbers are:<br />
 * <br />
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...<br />
 * <br />
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 22 = 48, is not pentagonal.<br />
 * <br />
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of
 * D?
 * 
 * @author martin
 * 
 */
public class Problem44_PentagonNumbers implements ProblemInterface {

	@Override
	public void solve() {
		System.out.println("Problem 44: ?");
	}
}
