package com.walshcorp.projecteuler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author martin
 * 
 */
public class Problem2_EvenFibonacci implements ProblemInterface {
	@Override
	public void solve() {
		int sum = 0;
		int i = 0;
		int j = 1;
		int k = 0;

		for (k = i + j; k < 4000000; i = j, j = k, k = i + j) {
			if (k % 2 == 0) {
				sum += k;
			}
		}

		System.out.println("Problem 2: " + sum);
	}
}
